site_name: Albumentations Documentation

plugins:
  - mknotebooks:
     enable_default_jupyter_cell_styling: false
     enable_default_pandas_dataframe_styling: false
     execute: false
  - awesome-pages
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: false
            show_if_no_docstring: false
          selection:
            docstring_style: google  # this is the default
            docstring_options:
              replace_admonitions: yes
      watch:
        - /albumentations
  - mkdocs-simple-hooks:
      hooks:
        on_page_content: "hooks:external_links_target_blank"
  - macros

google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_TID"]
  - auto

markdown_extensions:
  - codehilite
  - attr_list
  - admonition
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: "white"
    accent: "white"
  custom_dir: custom_theme/
  logo: images/logo.png
  favicon: images/logo.png

extra_css:
  - https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css
  - css/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js
  - js/extra.js

repo_name: albumentations
repo_url: https://github.com/albumentations-team/albumentations
site_url: https://albumentations.ai/docs/

edit_uri: 'https://github.com/albumentations-team/albumentations.ai/tree/master/mkdocs/src/docs'

site_dir: /site
