site_name: Albumentations Documentation
nav:
  - Welcome: 'index.md'
  - Introduction:
    - 'What is image augmentation and how it can improve the performance of deep neural networks': 'introduction/image_augmentation.md'
    - 'Why you need a dedicated library for image augmentation': introduction/why_you_need_a_dedicated_library_for_image_augmentation.md
    - 'Why Albumentations': introduction/why_albumentations.md

plugins:
  - mknotebooks:
     enable_default_jupyter_cell_styling: false
     enable_default_pandas_dataframe_styling: false
  - search:
      prebuild_index: true

features:
- tabs

google_analytics:
  - UA-158065353-1
  - auto

markdown_extensions:
  - codehilite
  - attr_list
  - admonition

theme:
  name: material
  palette:
    primary: "white"
    accent: "white"
  custom_dir: custom_theme/
  logo: images/logo.png
  favicon: images/logo.png

extra_css:
  - css/extra.css

repo_name: albumentations
repo_url: https://github.com/albumentations-team/albumentations
site_url: https://albumentations.ai

edit_uri: 'https://github.com/albumentations-team/albumentations.ai/tree/master/mkdocs/src/docs'

site_dir: /site
